name: Rust

on:
  push:
    branches: [ "testing" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  LIBCLANG_PATH: "/usr/lib/llvm-14/lib"

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update -yqq
        sudo apt-get install -yqq cmake pkg-config
        sudo apt-get install -yqq libasound2-dev libx11-dev libxrandr-dev libxi-dev libgl1-mesa-dev libglu1-mesa-dev libxcursor-dev libxinerama-dev
        sudo apt-get install -yqq llvm-14 libclang-14-dev clang-14

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Run clippy
      run: |
        rustup component add clippy
        cargo clippy -- -D warnings
